version: '3'
services:
  # NATS SERVER
  nats-server:
    image: nats:2.11.2
  # CLIENT GATEWAY
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservice-shop-nest/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  # AUTH MICROSERVICE
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservice-shop-nest/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  # PRODUCTS MICROSERVICE
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservice-shop-nest/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  # ORDERS MICROSERVICE
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image: northamerica-south1-docker.pkg.dev/microservice-shop-nest/image-registry/orders-ms
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DB_URL}
      - NATS_SERVERS=nats://nats-server:4222
  # PAYMENTS MICROSERVICE - STRIPE
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservice-shop-nest/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
